# Generated by Django 4.1.2 on 2023-09-17 16:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('author_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='作者ID')),
                ('author_name', models.CharField(max_length=100, verbose_name='作者名')),
            ],
        ),
        migrations.CreateModel(
            name='Genrue',
            fields=[
                ('genrue_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ジャンルID')),
                ('genrue_name', models.CharField(max_length=10, verbose_name='ジャンル')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_link', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('series_name', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='シリーズ名')),
                ('nyaa_keyword', models.CharField(blank=True, max_length=255, null=True, verbose_name='Torrent検索')),
                ('confirm_date', models.DateField(default=django.utils.timezone.now, verbose_name='確認日')),
                ('slug', models.SlugField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('status_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ステータスID')),
                ('status_name', models.CharField(max_length=4, verbose_name='ステータス')),
            ],
        ),
        migrations.CreateModel(
            name='Workbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process', models.CharField(blank=True, max_length=10, null=True)),
                ('path', models.CharField(max_length=255)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('genrue_id', models.IntegerField(default=1)),
                ('genrue_name', models.CharField(blank=True, error_messages='20文字以下で入力してください。', max_length=20, null=True)),
                ('story_by_id', models.IntegerField(null=True)),
                ('story_by', models.CharField(max_length=20, null=True)),
                ('art_by', models.CharField(blank=True, max_length=20, null=True)),
                ('art_by_id', models.IntegerField(null=True)),
                ('book_id', models.IntegerField(null=True)),
                ('title', models.CharField(max_length=50, null=True)),
                ('sub_title', models.CharField(blank=True, max_length=50, null=True)),
                ('volume', models.CharField(blank=True, max_length=5, null=True)),
                ('book_name', models.CharField(blank=True, max_length=255, null=True)),
                ('save_path', models.CharField(blank=True, max_length=255, null=True)),
                ('exist_flg', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Path',
            fields=[
                ('genrue', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='book.genrue', verbose_name='ジャンル')),
                ('path', models.CharField(max_length=255, verbose_name='パス')),
            ],
        ),
        migrations.CreateModel(
            name='Torrent',
            fields=[
                ('title', models.TextField()),
                ('torrent_link', models.TextField(primary_key=True, serialize=False)),
                ('img_link', models.TextField(blank=True, null=True)),
                ('downloaded', models.BooleanField(default=False)),
                ('regist_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('adult_flg', models.BooleanField(default=False)),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='torrent', to='book.series')),
            ],
        ),
        migrations.AddField(
            model_name='series',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.status', verbose_name='状態'),
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('book_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='書籍ID')),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('sub_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='サブタイトル')),
                ('art_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='art_by_id', to='book.author', verbose_name='作画')),
                ('genrue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.genrue', verbose_name='ジャンル')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='book.series', verbose_name='シリーズ名')),
                ('status', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='book.status', verbose_name='ステータス')),
                ('story_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_by_id', to='book.author', verbose_name='原作者')),
                ('save_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.path', verbose_name='保存先')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_name', models.CharField(max_length=255, verbose_name='書籍名')),
                ('file_path', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='ファイルパス')),
                ('volume', models.CharField(blank=True, max_length=3, null=True, verbose_name='巻数')),
                ('read_flg', models.BooleanField(default=False, verbose_name='既読フラグ')),
                ('regist_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='登録日')),
                ('isPdf', models.BooleanField(default=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book', to='book.info', verbose_name='書籍情報')),
                ('genrue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.genrue', verbose_name='ジャンル')),
            ],
        ),
    ]
