# Generated by Django 4.1.2 on 2022-11-19 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genrue_id', models.IntegerField()),
                ('genrue_name', models.CharField(max_length=255)),
                ('book_id', models.IntegerField()),
                ('book_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=255)),
                ('volume', models.CharField(blank=True, max_length=3, null=True)),
                ('read_flg', models.BooleanField(default=False)),
                ('regist_date', models.DateField()),
            ],
        ),
    ]
