# Generated by Django 3.2.15 on 2022-09-23 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Torrent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('torrent_link', models.TextField()),
                ('img_link', models.TextField()),
            ],
        ),
    ]
