# Generated by Django 3.2.15 on 2022-09-23 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torrent',
            name='img_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='torrent',
            name='torrent_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
