# Generated by Django 4.1.2 on 2023-10-01 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryBy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_by', models.CharField(max_length=255, verbose_name='作者')),
            ],
        ),
    ]
