# Generated by Django 4.1.2 on 2022-11-19 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='genrue',
            fields=[
                ('genrue_id', models.IntegerField(primary_key=True, serialize=False)),
                ('genrue_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='status',
            fields=[
                ('status_id', models.IntegerField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(max_length=255)),
            ],
        ),
    ]
