# Generated by Django 4.1.2 on 2022-11-19 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_genrue_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='author',
            fields=[
                ('author_id', models.IntegerField(primary_key=True, serialize=False)),
                ('author_name', models.CharField(max_length=255)),
                ('genrue_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Torrent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('torrent_link', models.TextField()),
                ('img_link', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Workbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process', models.CharField(blank=True, max_length=10, null=True)),
                ('path', models.CharField(max_length=255)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('genrue_id', models.IntegerField(default=1)),
                ('genrue_name', models.CharField(blank=True, max_length=10, null=True)),
                ('author_id', models.IntegerField(null=True)),
                ('story_by', models.CharField(blank=True, max_length=20, null=True)),
                ('art_by', models.CharField(blank=True, max_length=20, null=True)),
                ('book_id', models.IntegerField(null=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('sub_title', models.CharField(blank=True, max_length=50, null=True)),
                ('volume', models.IntegerField(null=True)),
                ('book_name', models.CharField(blank=True, max_length=255, null=True)),
                ('save_path', models.CharField(blank=True, max_length=255, null=True)),
                ('exist_flg', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='info',
            fields=[
                ('book_id', models.IntegerField(primary_key=True, serialize=False)),
                ('story_by_id', models.IntegerField()),
                ('story_by', models.CharField(blank=True, max_length=255, null=True)),
                ('art_by_id', models.IntegerField()),
                ('art_by', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_title', models.CharField(blank=True, max_length=255, null=True)),
                ('save_path', models.CharField(blank=True, max_length=255, null=True)),
                ('confirm_date', models.DateField()),
                ('genrue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.genrue')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.status')),
            ],
        ),
    ]
