# Generated by Django 3.2.15 on 2022-10-10 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20220924_0000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process', models.CharField(blank=True, max_length=255, null=True)),
                ('path', models.CharField(max_length=255)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('genrue_id', models.IntegerField(default=1)),
                ('genrue_name', models.CharField(blank=True, max_length=255, null=True)),
                ('author_id', models.IntegerField(null=True)),
                ('story_by', models.CharField(blank=True, max_length=255, null=True)),
                ('art_by', models.CharField(blank=True, max_length=255, null=True)),
                ('book_id', models.IntegerField(null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_title', models.CharField(blank=True, max_length=255, null=True)),
                ('volume', models.IntegerField(null=True)),
                ('book_name', models.CharField(blank=True, max_length=255, null=True)),
                ('save_path', models.CharField(blank=True, max_length=255, null=True)),
                ('exist_flg', models.BooleanField()),
            ],
        ),
    ]
