# Generated by Django 4.1.2 on 2023-10-01 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_storyby'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StoryBy',
        ),
        migrations.RemoveField(
            model_name='author',
            name='author_id',
        ),
        migrations.AddField(
            model_name='author',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
