# Generated by Django 4.1.2 on 2022-11-19 14:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_author_torrent_workbook_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='torrent',
            name='regist_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
