# Generated by Django 4.1.2 on 2023-10-07 14:37

from django.db import migrations, models

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_remove_info_book_id_info_id'),
    ]

    operations = [
         migrations.CreateModel(
            name='Book',
            fields=[
                ('book_name', models.CharField(max_length=255, verbose_name='書籍名')),
                ('file_path', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='ファイルパス')),
                ('volume', models.CharField(blank=True, max_length=3, null=True, verbose_name='巻数')),
                ('read_flg', models.BooleanField(default=False, verbose_name='既読フラグ')),
                ('regist_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='登録日')),
                ('isPdf', models.BooleanField(default=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book', to='book.info', verbose_name='書籍情報')),
                ('genrue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.genrue', verbose_name='ジャンル')),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='isPdf',
            field=models.BooleanField(default=True, verbose_name='拡張子'),
        ),
    ]
