# Generated by Django 4.1.2 on 2022-11-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_torrent_regist_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='torrent',
            name='downloaded',
            field=models.BooleanField(default=False),
        ),
    ]
