# Generated by Django 4.1.2 on 2022-11-20 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_torrent_downloaded'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_link', models.CharField(max_length=255)),
            ],
        ),
    ]
