# Generated by Django 4.1.2 on 2023-10-08 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_alter_book_ispdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kana', models.CharField(max_length=2, verbose_name='読み仮名')),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='ana',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.kana'),
        ),
    ]
