# Generated by Django 4.1.2 on 2022-11-20 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='story_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='workbook',
            name='volume',
            field=models.FloatField(null=True),
        ),
    ]
