# Generated by Django 4.1.2 on 2023-11-23 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_rename_ana_author_kana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='kana',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.kana', verbose_name='読み仮名'),
        ),
        migrations.AlterField(
            model_name='book',
            name='volume',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='巻数'),
        ),
    ]
