# Generated by Django 4.1.2 on 2023-11-25 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0003_rename_groups_adult_group'),
        ('book', '0008_alter_author_kana_alter_book_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='anime.category', verbose_name='カテゴリー'),
        ),
    ]
