# Generated by Django 4.1.2 on 2022-12-10 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_alter_workbook_story_by_alter_workbook_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='art_by',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='author_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='story_by',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='sub_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
