# Generated by Django 4.1.2 on 2022-12-10 14:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_book_art_by_book_author_id_book_story_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author_id',
            new_name='art_by_id',
        ),
        migrations.AddField(
            model_name='book',
            name='story_by_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='regist_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='book',
            name='story_by',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
