# Generated by Django 4.1.2 on 2022-12-10 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0013_rename_author_id_book_art_by_id_book_story_by_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='art_by_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='story_by_id',
            field=models.IntegerField(),
        ),
    ]
