# Generated by Django 4.1.2 on 2022-12-11 03:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0014_alter_book_art_by_id_alter_book_story_by_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workbook',
            old_name='author_id',
            new_name='art_by_id',
        ),
        migrations.AddField(
            model_name='workbook',
            name='story_by_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='confirm_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
