# Generated by Django 4.1.2 on 2023-01-14 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0020_alter_book_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='slug',
        ),
    ]
