# Generated by Django 4.1.2 on 2023-01-14 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0021_remove_book_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
