# Generated by Django 4.1.2 on 2023-01-15 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0022_book_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='file_path',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
