# Generated by Django 4.1.2 on 2023-01-15 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0023_alter_book_file_path_alter_book_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='file_path',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
