# Generated by Django 4.1.2 on 2023-01-20 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0024_alter_book_file_path_alter_book_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='torrent',
            name='book_id',
            field=models.IntegerField(null=True),
        ),
    ]
