# Generated by Django 4.1.2 on 2023-02-25 09:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0026_alter_book_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='regist_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
