# Generated by Django 4.1.2 on 2023-03-12 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0027_alter_book_regist_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('series_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
            ],
        ),
    ]
