# Generated by Django 4.1.2 on 2023-03-12 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0028_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='keyword',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='book.status'),
            preserve_default=False,
        ),
    ]
