# Generated by Django 4.1.2 on 2023-04-03 13:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0029_series_keyword_series_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='series_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='book.series'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='series',
            name='confirm_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
