# Generated by Django 4.1.2 on 2023-04-06 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0030_book_series_id_series_confirm_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='series_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book', to='book.series'),
        ),
        migrations.AlterField(
            model_name='series',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
