# Generated by Django 4.1.2 on 2023-04-08 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0031_alter_book_series_id_alter_series_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='workbook',
            name='series',
            field=models.IntegerField(null=True),
        ),
    ]
