# Generated by Django 4.1.2 on 2023-04-08 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0032_workbook_series'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workbook',
            name='series',
        ),
    ]
