# Generated by Django 4.1.2 on 2023-04-08 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0033_remove_workbook_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='series',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='book.series'),
            preserve_default=False,
        ),
    ]
