# Generated by Django 4.1.2 on 2023-04-08 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0034_info_series'),
    ]

    operations = [
        migrations.RenameField(
            model_name='series',
            old_name='title',
            new_name='series_name',
        ),
        migrations.AlterField(
            model_name='info',
            name='art_by_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='art_by_id', to='book.author'),
        ),
        migrations.AlterField(
            model_name='info',
            name='story_by_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_by_id', to='book.author'),
        ),
    ]
