# Generated by Django 4.1.2 on 2023-04-08 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0035_rename_title_series_series_name_alter_info_art_by_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='art_by',
        ),
        migrations.RemoveField(
            model_name='info',
            name='story_by',
        ),
    ]
