# Generated by Django 4.1.2 on 2023-04-08 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0037_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='path',
            name='id',
        ),
        migrations.AlterField(
            model_name='path',
            name='genrue_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='book.genrue'),
        ),
    ]
