# Generated by Django 4.1.2 on 2023-04-08 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0038_remove_path_id_alter_path_genrue_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='path',
            old_name='genrue_id',
            new_name='genrue',
        ),
    ]
