# Generated by Django 4.1.2 on 2023-04-08 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0039_rename_genrue_id_path_genrue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='save_path',
        ),
    ]
