# Generated by Django 4.1.2 on 2023-04-08 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0040_remove_info_save_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='art_by_id',
            new_name='art_by',
        ),
        migrations.RenameField(
            model_name='info',
            old_name='story_by_id',
            new_name='story_by',
        ),
    ]
