# Generated by Django 4.1.2 on 2023-04-08 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0041_rename_art_by_id_info_art_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='path',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='path',
            name='genrue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.genrue', unique=True),
        ),
    ]
