# Generated by Django 4.1.2 on 2023-04-08 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0042_path_id_alter_path_genrue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='path',
            name='genrue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.genrue'),
        ),
    ]
