# Generated by Django 4.1.2 on 2023-04-08 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0045_remove_path_id_alter_path_genrue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genrue',
            name='genrue_name',
            field=models.CharField(max_length=6),
        ),
    ]
