# Generated by Django 4.1.2 on 2023-04-08 11:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0046_alter_genrue_genrue_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='series_id',
            new_name='series',
        ),
        migrations.RemoveField(
            model_name='author',
            name='genrue_id',
        ),
        migrations.RemoveField(
            model_name='book',
            name='art_by',
        ),
        migrations.RemoveField(
            model_name='book',
            name='art_by_id',
        ),
        migrations.RemoveField(
            model_name='book',
            name='book_id',
        ),
        migrations.RemoveField(
            model_name='book',
            name='genrue_id',
        ),
        migrations.RemoveField(
            model_name='book',
            name='genrue_name',
        ),
        migrations.RemoveField(
            model_name='book',
            name='story_by',
        ),
        migrations.RemoveField(
            model_name='book',
            name='story_by_id',
        ),
        migrations.RemoveField(
            model_name='book',
            name='sub_title',
        ),
        migrations.RemoveField(
            model_name='book',
            name='title',
        ),
        migrations.RemoveField(
            model_name='info',
            name='confirm_date',
        ),
        migrations.RemoveField(
            model_name='series',
            name='keyword',
        ),
        migrations.AddField(
            model_name='author',
            name='genrue',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='book.genrue', verbose_name='ジャンル'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='book.info', verbose_name='書籍情報'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='genrue',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='book.genrue', verbose_name='ジャンル'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='info',
            name='save_path',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='book.path', verbose_name='保存先'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='series',
            name='nyaa_keyword',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Torrent検索'),
        ),
        migrations.AlterField(
            model_name='author',
            name='author_id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='作者ID'),
        ),
        migrations.AlterField(
            model_name='author',
            name='author_name',
            field=models.CharField(max_length=255, verbose_name='作者名'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_name',
            field=models.CharField(max_length=255, verbose_name='書籍名'),
        ),
        migrations.AlterField(
            model_name='book',
            name='file_path',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='ファイルパス'),
        ),
        migrations.AlterField(
            model_name='book',
            name='read_flg',
            field=models.BooleanField(default=False, verbose_name='既読フラグ'),
        ),
        migrations.AlterField(
            model_name='book',
            name='regist_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='登録日'),
        ),
        migrations.AlterField(
            model_name='book',
            name='volume',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='巻数'),
        ),
        migrations.AlterField(
            model_name='genrue',
            name='genrue_id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='ジャンルID'),
        ),
        migrations.AlterField(
            model_name='genrue',
            name='genrue_name',
            field=models.CharField(max_length=6, verbose_name='ジャンル'),
        ),
        migrations.AlterField(
            model_name='info',
            name='art_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='art_by_id', to='book.author', verbose_name='作画'),
        ),
        migrations.AlterField(
            model_name='info',
            name='book_id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='書籍ID'),
        ),
        migrations.AlterField(
            model_name='info',
            name='genrue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.genrue', verbose_name='ジャンル'),
        ),
        migrations.AlterField(
            model_name='info',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.series', verbose_name='シリーズ'),
        ),
        migrations.AlterField(
            model_name='info',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.status', verbose_name='ステータス'),
        ),
        migrations.AlterField(
            model_name='info',
            name='story_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_by_id', to='book.author', verbose_name='原作者'),
        ),
        migrations.AlterField(
            model_name='info',
            name='sub_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='サブタイトル'),
        ),
        migrations.AlterField(
            model_name='info',
            name='title',
            field=models.CharField(max_length=255, verbose_name='タイトル'),
        ),
        migrations.AlterField(
            model_name='path',
            name='genrue',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='book.genrue', verbose_name='ジャンル'),
        ),
        migrations.AlterField(
            model_name='path',
            name='path',
            field=models.CharField(default=1, max_length=255, verbose_name='パス'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='series',
            name='confirm_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='確認日'),
        ),
        migrations.AlterField(
            model_name='series',
            name='series_id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='シリーズID'),
        ),
        migrations.AlterField(
            model_name='series',
            name='series_name',
            field=models.CharField(max_length=255, verbose_name='ステータス名'),
        ),
        migrations.AlterField(
            model_name='series',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.status', verbose_name='状態'),
        ),
        migrations.AlterField(
            model_name='status',
            name='status_id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='ステータスID'),
        ),
        migrations.AlterField(
            model_name='status',
            name='status_name',
            field=models.CharField(max_length=4, verbose_name='ステータス'),
        ),
    ]
