# Generated by Django 4.1.2 on 2023-04-09 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0048_alter_info_art_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='path',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='genrue',
            name='genrue_name',
            field=models.CharField(max_length=10, verbose_name='ジャンル'),
        ),
        migrations.AlterField(
            model_name='workbook',
            name='genrue_name',
            field=models.CharField(blank=True, error_messages='20文字以下で入力してください。', max_length=20, null=True),
        ),
    ]
