# Generated by Django 4.1.2 on 2023-04-09 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0049_image_path_alter_genrue_genrue_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='torrent',
            name='book_id',
        ),
        migrations.RemoveField(
            model_name='torrent',
            name='genrue_id',
        ),
        migrations.RemoveField(
            model_name='torrent',
            name='img_link',
        ),
        migrations.AddField(
            model_name='torrent',
            name='series',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='book.series'),
            preserve_default=False,
        ),
    ]
