# Generated by Django 4.1.2 on 2023-04-09 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0050_remove_torrent_book_id_remove_torrent_genrue_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='torrent',
            name='adult_flg',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='torrent',
            name='img_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
