# Generated by Django 4.1.2 on 2023-04-09 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0052_alter_torrent_adult_flg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torrent',
            name='adult_flg',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='torrent',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.series'),
        ),
    ]
