# Generated by Django 4.1.2 on 2023-04-10 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0053_alter_torrent_adult_flg_alter_torrent_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isPdf',
            field=models.BooleanField(default=True),
        ),
    ]
