# Generated by Django 4.1.2 on 2023-04-16 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0054_book_ispdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='genrue',
        ),
        migrations.AddField(
            model_name='author',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, verbose_name='キー'),
        ),
    ]
