# Generated by Django 4.1.2 on 2023-04-16 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0055_remove_author_genrue_author_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='slug',
        ),
    ]
