# Generated by Django 4.1.2 on 2023-04-16 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0056_remove_author_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_name',
            field=models.CharField(max_length=100, verbose_name='作者名'),
        ),
        migrations.AlterField(
            model_name='book',
            name='series',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='series',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='series_id',
            field=models.IntegerField(verbose_name='シリーズID'),
        ),
        migrations.AlterField(
            model_name='series',
            name='series_name',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='シリーズ名'),
        ),
        migrations.AlterField(
            model_name='torrent',
            name='series',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
