# Generated by Django 4.1.2 on 2023-04-16 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0057_alter_author_author_name_alter_book_series_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torrent',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.series'),
        ),
    ]
