# Generated by Django 4.1.2 on 2023-04-16 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0059_alter_book_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='series',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='book.series', verbose_name='シリーズ名'),
            preserve_default=False,
        ),
    ]
