# Generated by Django 4.1.2 on 2023-04-21 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0062_remove_series_series_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='series',
        ),
        migrations.AlterField(
            model_name='info',
            name='status',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='book.status', verbose_name='ステータス'),
        ),
    ]
