# Generated by Django 4.1.2 on 2023-04-23 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0063_remove_book_series_alter_info_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='slug',
            field=models.SlugField(max_length=255, null=True),
        ),
    ]
