# Generated by Django 4.1.2 on 2023-04-23 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0064_series_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book', to='book.info', verbose_name='書籍情報'),
        ),
        migrations.AlterField(
            model_name='info',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='book.series', verbose_name='シリーズ名'),
        ),
    ]
