# Generated by Django 4.1.2 on 2023-04-30 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0065_alter_book_book_alter_info_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torrent',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='torrent', to='book.series'),
        ),
    ]
