# Generated by Django 4.1.2 on 2023-05-01 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0066_alter_torrent_series'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='torrent',
            name='id',
        ),
        migrations.AlterField(
            model_name='torrent',
            name='torrent_link',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
