# Generated by Django 3.2.15 on 2022-09-25 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='dtEnd',
            field=models.DateField(blank=True, null=True, verbose_name='放送終了日'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='dtStart',
            field=models.DateField(blank=True, null=True, verbose_name='放送開始日'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='keyword',
            field=models.CharField(max_length=255, verbose_name='torrent検索ワード'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='title',
            field=models.CharField(max_length=255, verbose_name='タイトル'),
        ),
    ]
