# Generated by Django 3.2.15 on 2022-09-25 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_auto_20220925_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='episode',
            field=models.IntegerField(null=True, verbose_name='話数'),
        ),
    ]
