# Generated by Django 4.1.2 on 2023-09-18 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_rename_group_adult_groups'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adult',
            old_name='groups',
            new_name='group',
        ),
    ]
