# Generated by Django 3.2.15 on 2022-09-25 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0004_anime_lastepisode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='episode',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='lastEpisode',
        ),
    ]
