# Generated by Django 3.2.15 on 2022-09-25 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0005_auto_20220925_2333'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('episode', models.IntegerField()),
                ('lastEpisode', models.IntegerField()),
                ('path', models.CharField(max_length=255, verbose_name='パス')),
            ],
        ),
    ]
