# Generated by Django 3.2.15 on 2022-10-01 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0007_torrent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='lastEpisode',
        ),
    ]
