# Generated by Django 3.2.15 on 2022-10-01 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0008_remove_video_lastepisode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='id',
        ),
        migrations.AlterField(
            model_name='video',
            name='path',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='パス'),
        ),
    ]
