# Generated by Django 3.2.15 on 2022-10-01 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0010_auto_20221001_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torrent',
            name='title',
            field=models.TextField(verbose_name='Torrent'),
        ),
        migrations.AlterField(
            model_name='torrent',
            name='torrent_link',
            field=models.TextField(primary_key=True, serialize=False, verbose_name='Torrentリンク'),
        ),
        migrations.AlterField(
            model_name='video',
            name='episode',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='話数'),
        ),
    ]
