# Generated by Django 3.2.15 on 2022-10-01 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0011_auto_20221001_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='group',
            field=models.CharField(default=1, max_length=255, verbose_name='グループ'),
            preserve_default=False,
        ),
    ]
