# Generated by Django 3.2.15 on 2022-10-01 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0012_video_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='group',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='グループ'),
        ),
    ]
