# Generated by Django 3.2.15 on 2022-10-01 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0013_alter_video_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='video',
            name='episode',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='話数'),
        ),
    ]
