# Generated by Django 3.2.15 on 2022-10-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0014_auto_20221002_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='keyword',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='torrent検索ワード'),
        ),
    ]
