# Generated by Django 3.2.15 on 2022-10-09 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0015_alter_anime_keyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anime',
            name='dtEnd',
            field=models.DateField(verbose_name='放送終了日'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='dtStart',
            field=models.DateField(verbose_name='放送開始日'),
        ),
        migrations.AlterField(
            model_name='video',
            name='path',
            field=models.CharField(max_length=255, verbose_name='パス'),
        ),
    ]
