# Generated by Django 3.2.15 on 2022-10-10 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0017_video_process'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='dtEnd',
            field=models.DateField(verbose_name='Broadcast end date'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='dtStart',
            field=models.DateField(verbose_name='Broadcast start date'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='keyword',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Search torrent word'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
    ]
