# Generated by Django 3.2.15 on 2022-10-10 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0018_auto_20221010_1223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, verbose_name='パス')),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('episode', models.CharField(blank=True, max_length=2, null=True, verbose_name='話数')),
                ('group', models.CharField(blank=True, max_length=255, null=True, verbose_name='グループ')),
                ('url', models.CharField(blank=True, max_length=255, null=True, verbose_name='URL')),
                ('process', models.CharField(blank=True, max_length=20, null=True, verbose_name='処理')),
            ],
        ),
    ]
