# Generated by Django 4.1.2 on 2022-10-29 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0019_adult'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='isEnd',
            field=models.BooleanField(null=True),
        ),
    ]
