# Generated by Django 4.1.2 on 2023-01-14 01:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0021_alter_adult_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='torrent',
            name='dtRegist',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 14, 1, 51, 39, 451058, tzinfo=datetime.timezone.utc)),
        ),
    ]
