# Generated by Django 4.1.2 on 2023-01-14 02:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0022_torrent_dtregist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torrent',
            name='dtRegist',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
