# Generated by Django 4.1.2 on 2023-03-12 02:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0023_alter_torrent_dtregist'),
    ]

    operations = [
        migrations.AddField(
            model_name='adult',
            name='dtRegist',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='登録日'),
        ),
        migrations.AddField(
            model_name='video',
            name='dtRegist',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='登録日'),
        ),
        migrations.AlterField(
            model_name='torrent',
            name='dtRegist',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='登録日'),
        ),
    ]
