# Generated by Django 4.1.2 on 2023-03-18 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0025_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='period',
            name='yearmonth',
        ),
        migrations.AddField(
            model_name='period',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
