# Generated by Django 4.1.2 on 2023-03-18 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0026_remove_period_yearmonth_period_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='period',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='anime.period'),
            preserve_default=False,
        ),
    ]
