# Generated by Django 4.1.2 on 2023-03-21 13:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0028_alter_video_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='adult',
            name='dtRecent',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='最近視聴'),
        ),
    ]
