# Generated by Django 4.1.2 on 2023-05-06 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0029_adult_dtrecent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title'),
        ),
    ]
