# Generated by Django 4.1.2 on 2023-08-14 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0030_alter_anime_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255, verbose_name='カテゴリ')),
                ('adult_flg', models.BooleanField(blank=True, null=True, verbose_name='アダルト')),
            ],
        ),
    ]
