# Generated by Django 4.1.2 on 2023-08-14 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0031_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='adult',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='anime.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adult',
            name='score',
            field=models.IntegerField(blank=True, null=True, verbose_name='評価'),
        ),
    ]
