# Generated by Django 4.1.2 on 2023-08-14 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0032_adult_category_adult_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adult',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='anime.category'),
        ),
    ]
