# Generated by Django 4.1.2 on 2023-08-16 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0033_alter_adult_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adult',
            name='category',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
