# Generated by Django 4.1.2 on 2023-08-20 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0035_remove_category_id_category_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='kana',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='読み仮名'),
        ),
    ]
