# Generated by Django 4.1.2 on 2023-08-20 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0036_category_kana'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kana', models.CharField(max_length=2, verbose_name='読み仮名')),
            ],
        ),
    ]
