# Generated by Django 4.1.2 on 2023-08-20 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0037_kana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='kana',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='anime.kana'),
        ),
    ]
